import "./globals.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.min.css";
import GlobalContextProvider from "./GlobalContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <GlobalContextProvider>
          {children}
          <ToastContainer hideProgressBar />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
